### ISSUE TITLE
v8 release date

### ISSUE THREAD

**Issue by rebootcode** [go-siris/siris#26]
Hi, While i see lots of activity happening in the siris ( fork of IRIS ) i am eager to know release date of siris v8 .

Is there any deadline or release date for v8 with all checked improvements and siris being independent.

**Comment by Allendar** [comment]
Could you describe what you would be expecting? v8 is probably not coming for quite some time, as the features that are currently being thought out are minor patches at most.

Independence is already built-in, because of committed vendoring. There's no use to reinvent the wheel when so many people did all that amazing work already. Even if those repositories would disappear for some reason, it would still be in the Siris repo and could easily be moved inside as a dedicated subpackage.

**Comment by rebootcode** [comment]
Hi Allendar, I am expecting these := https://github.com/go-siris/siris/projects/1

Thanks for taking your time and keeping IRIS Alive.
