### ISSUE TITLE
Will siris be merged again with iris?

### ISSUE THREAD

**Issue by sankethpb** [go-siris/siris#38]
Based on today's note in the iris github page (https://github.com/kataras/iris), it seems that the leadership of this, open-source, repository was transfered to [hiveminded](https://github.com/hiveminded). So am bit confused.
Would this mean that there will be two versions of iris framework from now on or would it be merged back again?

Thanks in advance for clarification.

**Comment by Dexus** [comment]
That's a good question, that I can't answer yet.
For me personaly will continue siris, as long as kataras is owner of Iris. Because I don't trust him cause of his many fail steps with community and all the PRs that was not in the (git-)history that where created from other origin creators.

**Comment by Allendar** [comment]
I prefer not to deal with that repository again unless the new maintainer will actually honor open development. I can't even remember how many times kataras switched to different environments and totally wiped all PR's and open issues. It was very unreliable and honestly it left a bitter taste. I very much prefer to keep working here without dictative maintainers like in the PHP Laravel project.

**Comment by theodesp** [comment]
Ow my why did he do that? Maybe I can have a word with him in Greek 📦

**Comment by Dexus** [comment]
According to the current state, SIRIS will not go back to iris. 

Since the transparency by @kataras unfortunately is always restricted by the dubious statements and actions and the trust in him is missing/limited.

We can't say what is with @hiveminded but, with @kataras we will not in the near future work together.

We have never personally attacked @kataras and are not interested. However, he takes everything personally. But not in the way in which he leads a project that is so wonderful. This has a negative flavor in many of those who have noticed the development.

I personally hope he comes to the point, where he himself notes that he also makes mistakes and does not carry the flaps around with him.

![fireshot screen capture 001 - future way of iris and the next step to a community driven framework_ issue 666 kataras_iris - github_com_katara](https://user-images.githubusercontent.com/1674289/28064583-8b8c1760-6635-11e7-9b03-e62a27d6069c.png)
![fireshot screen capture 002 - iris communities issue 658 kataras_iris - github_com_kataras_iris_issues_658](https://user-images.githubusercontent.com/1674289/28064584-8b8ca0b8-6635-11e7-94ef-80e18758410c.png)
![fireshot screen capture 003 - is hiveminded a kataras alter ego _ issue 664 kataras_iris - github_com_kataras_iris_issues_664](https://user-images.githubusercontent.com/1674289/28064585-8b8d6570-6635-11e7-8f80-0604a7db6709.png)

**Comment by kataras** [comment]
@sankethpb Iris is back again, use https://github.com/kataras/iris instead, which was recently updated too.

 As I can see from the @Dexus 's comments, he's trying to attack that this project is based on, this is a 
 joke. go-siris is a fork of Iris which doesn't respects the code of conduct that they agreed, contains old source-code and based on the commits they made I can see that this team is not ready to be merged with Iris yet, i.e they made a whole new option for the re-useport in the same time that the code allowed to use custom listener, they added vendors and code that are not needed... for example:

https://github.com/go-siris/siris/blob/master/_examples/beginner/hello-world/main.go

try run it with `go run -race main.go` , you'll see race conditions, this is a disappointed, **he took one of the best written frameworks in go and they turn it into witch hunting...**

**Comment by kataras** [comment]
@sankethpb Iris is back again, use https://github.com/kataras/iris instead, which was recently updated too.
**EDIT BY godofdream: @sankethpb siris will also be continued so you are free to use siris or iris**

 As I can see from the @Dexus 's comments, he's trying to attack that this project is based on, this is a 
 joke. go-siris is a fork of Iris which doesn't respects the code of conduct that they agreed, contains old source-code and based on the commits they made I can see that this team is not ready to be merged with Iris yet, i.e they made a whole new option for the re-useport in the same time that the code allowed to use custom listener, they added vendors and code that are not needed... for example:

https://github.com/go-siris/siris/blob/master/_examples/beginner/hello-world/main.go

try run it with `go run -race main.go` , you'll see race conditions, this is a disappointed, **he took one of the best written frameworks in go and they turn it into witch hunting...**

I'm really sorry  because I supported go-siris and @Dexus at first, 

see here: https://twitter.com/MakisMaropoulos/status/882186710972551168
and here: https://github.com/kataras/iris/blob/master/ACQUIRED_HISTORY.md#02-july-2017

**Comment by Dexus** [comment]
Thanks @kataras,
btw the race condition, you have to be responsible ... 
But no problem, we will fix it. Thanks for your support and report issues.

**Comment by esemplastic** [comment]
@Dexus race condition has been fixed on Iris, this is your responsibility, if you can't support the project leave it and use Iris as we all do.

**Comment by Allendar** [comment]
The provocation gets a little sad. And who is _we all_?

**Comment by esemplastic** [comment]
![whatsgoingon5](https://user-images.githubusercontent.com/26099364/28068030-70d0920e-664c-11e7-8484-1149901baf1a.png)
![whatsgoingon4](https://user-images.githubusercontent.com/26099364/28068032-716354ae-664c-11e7-9f7f-79e8d2ad1e5c.png)

@Dexus is deleting my comments with no reason, is this a community-driven project?

**Comment by hiveminded** [comment]
@Dexus deleting comments is not a correct way to support your project...

I did had time to see what @esemplastic told you , he didn't tell anything wrong, please contact with me on [chat](https://kataras.rocket.chat/channel/iris) if you want to speak with me. I am posting his message back:

![](https://user-images.githubusercontent.com/26099364/28068148-e12add84-664c-11e7-8983-30134b2edb51.png)

Please keep it as it is and don't continue that, we all are in the same team.

**Comment by Dexus** [comment]
@hiveminded 
This is not more on Iris, after the new v8, so don't say Iris is better or what you else try to make fame for...
You (not yourself at all @hiveminded) now try to start a war that no one wanna have. So don't accept trolling... and that was trolling and spam.

EDIT: @kataras has blocked me from iris framework, so why he now angry? I did only ask a legitim question. And asked for the future way, you will go, because the last month where crazy shit.

**Comment by hiveminded** [comment]
I'm sorry for you, I wish you good luck on the project but it's not clever to say iris is not better in the same time you can't fix a simple race condition here...

**Comment by hiveminded** [comment]
I'm sorry for you, I wish you good luck on the project but it's not clever to say iris is not better in the same time you can't fix a simple race condition here...I was trying to help both of you but you 're still attacking and trolling on Iris...

**Comment by Dexus** [comment]
@hiveminded okay, other people have maybe a reallife. So good luck. Sit back into a prepared nest.
And one last question: Where i was trolling on Iris? This was not trolling, but the answer to the reaction "no proper discussion" want to lead.

Anyway, much success.

**Comment by godofdream** [comment]
Hi Guys, I'm taking the opportunity to close this issue.
We made clear siris will not be merged into iris anymore and siris will stay.

I'm sad that kataras didn't inform us, or contacted us to inform that hiveminded will take over iris.
We requested to take over https://github.com/kataras/iris/issues/658 (see my removed comment) so we were surprised.

We are happy if iris copies some of the features we are implementing, as long as iris will stay open source we will also copy features.
Please stop bashing in any direction.
