### ISSUE TITLE
Possible License Violation

### ISSUE THREAD

**Issue by statusdevel** [go-siris/siris#48]
@Dexus some days ago you deleted a comment from @esemplastic but I was there to download his second attempt (he uploaded his screenshot to https://github.com/go-siris/siris/issues/39 ) :
![wts](https://user-images.githubusercontent.com/26099364/28236620-cfd41c74-6932-11e7-8ec5-d4b0e517a28c.png)

He just asked you why race conditions in this project while iris hadn't.

I gave you some time to see what you'll do and **how you will fix it** and you did the exactly thing again, you **pasted code from kataras/iris** repository and you removed the **license files**, **like it was yours**, proof of concept below.

The funny part is that you did that comment moments ago, how is that possible? You don't (or seems to not) respect his work but you're using his entire code and you're watching his repository to apply the same changes here too ?

![h](https://user-images.githubusercontent.com/26099364/28236615-b2df3b1c-6932-11e7-9f7f-81d8c9b850b5.png)

Except the whole repository, did you code anything by yourself or you always copy-pasting code from others?

**Fix/race condition/Rework core/nettools for easy resolve**

https://github.com/go-siris/siris/pull/44/commits/5e68f51441eac0b9724bc893f248b49e3a4cf876 (3 days old) is pasted code from https://github.com/kataras/iris/commit/4c76fca09bb632ed9a3bb3859a244e383c158bfd#diff-9fd01c8949c007d83e7a56c493a46398 pushed 5 days ago.

**Fix/race condition/Fix race condition and rework task managment.**

https://github.com/go-siris/siris/pull/44/commits/f7ced807c41b089b9e965625266140774ccc9dba (3 days old) is pasted code from
https://github.com/kataras/iris/commit/4c76fca09bb632ed9a3bb3859a244e383c158bfd#diff-93bf20dfbbddefa00c7d76a4090ab137 pushed 5 days ago, history notes about these changes can be also found [here](https://github.com/kataras/iris/blob/master/HISTORY.md#miscellaneous) .

You removed the license headers from https://github.com/go-siris/siris/pull/44/commits/f7ced807c41b089b9e965625266140774ccc9dba#diff-fcdeeccd045f157e84bc11bf6b7484bd too.

You tell the @go-siris community that you fixed sessions and you want reviews, are you kidding? 

You did copy-pasted again, this time not from @kataras but from @astaxie: 
https://github.com/go-siris/siris/pull/45/commits/7ea3143f60d2cecce17a93f9cea6498cd692204c#diff-9736e67342fce924fa0b8a4388ecfa79 (here you kept the hader files, but you did a PR telling that is your own code)

You, @Dexus, use his code as the big codebase, 
**you 're still copying his code into your fork but in the same time you're sprending that @kataras is not a good developer** -- what's the meaning of the fork if you never put your own things and only copying? and **why do people should use that fork?** you still have a **race condition on the first example** on readme.

**He's good developer and you use his framework and you watch his code everyday  or he is a bad developer and you don't use, copy or watch his code, you can't do both it's not logical.**

Beside all these, you're removing the header files from the go files(https://github.com/go-siris/siris/pull/44/commits/f7ced807c41b089b9e965625266140774ccc9dba#diff-fcdeeccd045f157e84bc11bf6b7484bd)

What's going on with you mate, do you ever learn?

The license also says that you should not comment the author of Iris in order promote a product (via him or other iris' contributor), you do exactly that.

@godofdream you and @Dexus are togeher, do you agree or you still support that guy? I remember when we were on the iris channel and @kataras helped you noumerous times, more than I can remember. He helped @Dexus too, he explained how go and net/http works to him some months ago, the whole @Dexus behavior shows that he is, at least, ungrateful.

> No offence

**Comment by Dexus** [comment]
First at all, why I should reinvent the wheel? For things that already there and works?
Licenses are there so I dont know what you see for problems.

When I have done something wrong, then I'm sorry. I will review and add then the left license or author.

**Comment by godofdream** [comment]
Hi Statusdevel. Welcome to Github. We will check if there is any license violation. I think we will start to add all authors to files, but as already kataras already removed so many authors it is hard to read them all.
By the way is there any software to find missing authors? Would be nice to autocomplete it.

@Dexus I will add the authors if the changes were made before your pullrequest.

**Comment by godofdream** [comment]
> He just asked you why race conditions in this project while iris hadn't.

Because we didn't know about it at that moment.
We deleted his comment because of the language he used.

> Except the whole repository, did you code anything by yourself or you always copy-pasting code from others?

Added reuseport, fixed some more errors.
Our project is relativly new, so give us some time to add the features we want to add.

**Comment by godofdream** [comment]
> 5e68f51 (3 days old) is pasted code from kataras/iris@4c76fca#diff-9fd01c8949c007d83e7a56c493a46398  pushed 5 days ago.

> f7ced80 (3 days old) is pasted code from
kataras/iris@4c76fca#diff-93bf20dfbbddefa00c7d76a4090ab137 pushed 5 days ago, history notes about these changes can be also found here .

kataras/iris is uses the BSD-3 License: 
https://github.com/kataras/iris/blob/4c76fca09bb632ed9a3bb3859a244e383c158bfd/LICENSE

The Siris LIcense File Mentions the iris project and the original author Gerasimos Maropoulos
https://github.com/go-siris/siris/blob/master/LICENSE
The BSD-3 License allows forking and redistribution and and and...
So there is no violation.

> You did copy-pasted again, this time not from @kataras but from @astaxie:
7ea3143#diff-9736e67342fce924fa0b8a4388ecfa79.

yes we copied  **some** code from the beego project, but the license headers were kept and original authors are still marked.
The Apache 2 License is compatible with the bsd3 license.


**Closing as there are no license Violations from the Siris Project.**
However there were license Violations in the past in the iris project. If some of these still apply please create a new issue.

EDIT: 
> Beside all these, you're removing the header files from the go files(f7ced80#diff-fcdeeccd045f157e84bc11bf6b7484bd)

They are unnecessary as the copyright of kataras is also in the License.

> the whole @Dexus  behavior shows that he is, at least, ungrateful.

we love the project, but we don't like what kataras does. I'm happy that dexus invests time in fixing and improving some o kataras code


> The license also says that you should not comment the author of Iris in order promote a product (via him or other iris' contributor), you do exactly that.

I can't see such thing. We mention him as original author of iris, nothing more.

> You, @Dexus, use his code as the big codebase,
you 're still copying his code into your fork but in the same time you're sprending that @kataras is not a good developer -- what's the meaning of the fork if you never put your own things and only copying? and why do people should use that fork? you still have a race condition on the first example on readme.

I at least liked version 6 of iris, than the API was changed, and in version 8 again... Then kataras sold iris...
I prefer a stable api that's why i searched for others to join forking iris.
I hoped siris to become the sucessor of iris, but kataras didn't like this idea, he even deleted our pledge of becomming the official community version of iris.

> He's good developer and you use his framework and you watch his code everyday or he is a bad developer and you don't use, copy or watch his code, you can't do both it's not logical.

Any developer has good days and bad days. But if i use it in production i need a stable api.
